### ISSUE TITLE
Cant install AtomSpaceExplorer 

### ISSUE THREAD

**Issue by manisabri** [opencog/external-tools#130]
It uses semantic-ui and it can not be installed with any recent version of gulp and node and many other packages. I worked with this node package before, it's abandoned and has issues ... ( kind of a nightmare tbh)

**Comment by ngeiswei** [comment]
I assum it's obsolete but I'm not sure. There's a new atomspace visualizer, @Habush might know about it.

**Comment by Habush** [comment]
@manisabri I tried to install it and ran into the same issues you mentioned. The way I fixed it is, 
1. Clean the node_modules cache
2. In `package.json` semantic-ui with **fomantic-ui** (it is the new port semantic ui by the community) and run `npm install`
3. Run `npm rebuild node-sass` (this might not be needed on your side, I just ran to an issue that said node-sass isn't supported on my platform, so rebuilding it fixed the error)

After the above steps, I was able to run and use the service with `npm start`

**Comment by manisabri** [comment]
No joy, 
Can you send your package.json and package-lock.json files?

**Comment by manisabri** [comment]
never mind I made it work just don't ask me how!

**Comment by linas** [comment]
can someone update some README with instructions on what to do? and/or push any required changes?

**Comment by Habush** [comment]
@manisabri can you share the issue you are having? or It'd be great if you shared the steps you took to resolve the issue

**Comment by manisabri** [comment]
um, well it's kina working now, except drop down menus that have something to do with jquery.
The first thing was this one 
https://stackoverflow.com/questions/55921442/how-to-fix-referenceerror-primordials-is-not-defined-in-node?page=2&tab=oldest#tab-top
then I removed semantic.js from angular-cli.json for another error and updated typescript to recent version for some other one. 
then I had to change some imports in python from flask.ext to flask_ext 
I think at some point I had change the node version back and forth for some stuff to compile 
Sorry I can't be more specific about it .... 
Is there gonna be a new atomspace visualizer around? if not I might spend more time on it

**Comment by linas** [comment]
> then I had to change

Why don't you send a pull request? maybe partly-fixed is better than nothing at all...

> a new atomspace visualizer 

I don't know. On very rare occasions, I use "gephi" and a highly customized atomspace exporter to export the stuff I'm interested in.

Writing a "generic" atomspace exporter (for gephi or graphviz or whatever) is hard because different datasets use different styles of encoding. They change over time .. the genome datases that MOZI uses are being changed to version 2 right now.  My datasets are completely different because they encode language, not genetics... visualizing either as "pure atoms" would be boring and confusing and cluttered.

It would be nice if someone wrote an exporter, where they user could supply the definition of a vertex, and the definition of an edge, and then export to gephi or whatever.  For example, to find all edges, one might have:
```
(cog-execute! (Get (VariableList (Variable "x") (Variable "y"))
   (Stuff (things (Variable "x") (morestuff (Variable "y") morethings)))
```
which then returns all x-y pairs that are the edges of whatever data you want to visualize. (BTW, I you don't regcognize `Get`, then you *must* do the tutorials here: https://github.com/opencog/atomspace/tree/master/examples )

This might be a useful practice exercise... and could grow into a real tool.... habush could hook you up with genomic datasets to practice with...

**Comment by manisabri** [comment]
sounds good. I'll try to polish things up a bit more in following pull request ...

**Comment by linas** [comment]
Closing because I assume #131 fixes remaining issues.
